name: Run Shell Commands
on: [push]

jobs: 
  run-shell-command:
    run-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello Security Gurus!!" This is our GitHub Actions Workflow file"
        
